### ISSUE TITLE
Message Management

### ISSUE THREAD

**Issue by sharils** [sharils/ncut-book-store#26]
# Message Management
## Message Creation

We need to allow an user to write a message to another user.
## Message Listing

We need to allow an user to see all messages he has sent and received. Sent
messages and received messages are separated.

This page must pass the W3C Markup Validation Service. http://validator.w3.org/

Style is not our concern at this moment.
## Message Detail

We need to allow an user to see details about a message.

In this detail page, an user can reply or delete the message.

**Comment by esbb48** [comment]
Detail 
button 傳值我可以用get嗎

**Comment by sharils** [comment]
用 get 或 post 取決與 form 的行為
