### ISSUE TITLE
User Module - Authenticate

### ISSUE THREAD

**Issue by sharils** [sharils/ncut-book-store#4]
## User authenticate(String sn, String sn, String password)

```
$user = User::authenticate($sn, $type, $password);
```

This method uses $sn and $type to find $user_id, and check if $user_id and
$password forms a pair it returns an instance of User. Otherwise it throws an
exception. What's thrown is yet to be defined.

**Comment by esbb48** [comment]
https://www.facebook.com/groups/464352556994768/465455060217851/
