### ISSUE TITLE
Update student class and type in database schema

### ISSUE THREAD

**Issue by sharils** [sharils/ncut-book-store#68]
student class is enum('a', 'b', 'c')
student type is enum('1a', '1b', '1c', '2a', '2b', '2c', '3a', '3b')

**Comment by esbb48** [comment]
我們把 '' 空值拿掉喔@@!

**Comment by esbb48** [comment]
Folio我們fb怪怪的開不太起來
科系的depar.....的部分
有固定十四個系 我們如果用enum的話
英文要打全部嗎 還是縮寫就OK了 
因為打全部的話 單字間的空白有關係嗎

**Comment by sharils** [comment]
英文沒縮寫嘛？是沒關係啦，但是可能不好用，可以把十四個科系的資料放給我看嗎？

**Comment by esbb48** [comment]
工業工程與管理系 IEM

企業管理系 BA

資訊管理系 IM ( 研發科技與資訊管理研究所 )

流通管理系

休閒產業管理系

文化創意事業系

景觀系

應用英語系

化工與材料工程系(所)

機械工程系(所) 

冷凍空調與能源系(所)

電機工程系(所)

電子工程系(所)

資訊工程系(所)

精密製造科技研究所(博士班) =>> 不熟悉

**Comment by sharils** [comment]
我來查縮寫

**Comment by sharils** [comment]
- Add course grade
- Add course system
- Rename type to system in the student table and change its data type to enum('1a', '1b', '1c', '2a', '2b', '2c', '3a', '3b')
- Change student department to enum('ae', 'ba', 'cc', 'cme', 'csie', 'ddm', 'dee', 'dlim', 'ee', 'iem', 'im', 'la', 'me', 'rac')

**Comment by hsy0130** [comment]
Add course semester enum('1','2')

**Comment by esbb48** [comment]
Change class to group
