### ISSUE TITLE
Use char only when the string length is fixed

### ISSUE THREAD

**Issue by sharils** [sharils/ncut-book-store#71]
There are some fields with char type. Fields that I don't think they are char:
- book.version
- course name
- publisher account
- publisher name

**Comment by esbb48** [comment]
book.version ,.. 因為是讓老師自己輸入可能是數字,國字,也可能是最新版.. (?) 
course name,publisher name 不是用char的話.. 那藥用varchar嗎(?
publisher account ... 網路上查可能有12. 14,所以用最大瑪做為限制@@?

**Comment by sharils** [comment]
一般來說，除非輸入的東西只會有固定長度，否則不會用 char。
那這幾個情況都是長度不固定，所以應該就直接換成 varchar
